/**
 * cifweb-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CifComplementoDtoId } from './cifComplementoDtoId';
import { CifServicoDto } from './cifServicoDto';
import { TipoVinculoDto } from './tipoVinculoDto';

export class CifComplementoDto { 
    cifServicoVinculado?: CifServicoDto;
    id?: CifComplementoDtoId;
    tipoVinculo?: TipoVinculoDto;
    icMandatorio?: string;

    public static of(cifServicoDto: CifServicoDto):CifComplementoDto { 
        let retorno = new CifComplementoDto();
        retorno.cifServicoVinculado = cifServicoDto;
        retorno.id = CifComplementoDtoId.of(cifServicoDto.id);
        return retorno;
    }
}