/**
 * cifweb-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CifComplementoDto } from './cifComplementoDto';
import { CifCoreografiaDto } from './cifCoreografiaDto';
import { CifServicoIdDto } from './cifServicoIdDto';
import { CifSrvcoPrpreFrmroDto } from './cifSrvcoPrpreFrmroDto';
import { SlctoManutencaoCifDto } from './slctoManutencaoCifDto';

export class CifServicoDto { 
    noServico?: string;
    id?: CifServicoIdDto;
    nuSubgrupo?: number;
    nuTipo?: number;
    nuSubtipo?: number;
    icServicoPrincipal?: string;
    complementos?: Array<CifComplementoDto>;
    cifCoreografias?: Array<CifCoreografiaDto>;
    cifSrvcoPrpreFrmros?: Array<CifSrvcoPrpreFrmroDto>;
    slctoManutencaoCifs?: Array<SlctoManutencaoCifDto>;
}